const mxCommerce = {
  "KIN-FID-ARTURITO": { price: 149, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-001": { price: 399, stock: 6, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-002": { price: 349, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FOC-001": { price: 1050, stock: null, enabled: true, stockStatus: "order_only" },
  "KIN-LOG-003": { price: 299, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-004": { price: 249, stock: 1, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-005": { price: 299, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-006": { price: 129, stock: 2, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-007": { price: 249, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-008": { price: 249, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-009": { price: 199, stock: 2, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-010": { price: 299, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-002": { price: 199, stock: 0, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-003": { price: 199, stock: 6, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-004": { price: 199, stock: 1, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-ESTRELLA": { price: 199, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-011": { price: 499, stock: 2, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-012": { price: 149, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-013": { price: 299, stock: 6, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-014": { price: 199, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-015": { price: 149, stock: 2, enabled: true, stockStatus: "in_stock" },
};
const crCommerce = {
  "KIN-FID-ARTURITO": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-001": { price: 13500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-002": { price: 18500, stock: 3, enabled: true, stockStatus: "in_stock" },
  "KIN-FOC-001": { price: 46500, stock: 2, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-003": { price: 10500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-004": { price: 9500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-005": { price: 11500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-006": { price: 9500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-007": { price: 11500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-008": { price: 11500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-009": { price: 16500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-010": { price: 11500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-002": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-003": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-004": { price: 9500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-FID-ESTRELLA": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-011": { price: 21500, stock: 3, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-012": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-013": { price: 9500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-014": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
  "KIN-LOG-015": { price: 8500, stock: 4, enabled: true, stockStatus: "in_stock" },
};
export const marketConfigs = {
  MX: {
    market: "MX",
    country: "México",
    locale: "es-MX",
    currency: "MXN",
    currencySymbol: "$",
    deliveryText: "Consulta opciones de entrega en México.",
    contact: {
      whatsapp: "525652069271",
      whatsappDisplay: "+52 56 5206 9271",
      instagramUrl: "https://www.instagram.com/kinoraneurostore/",
      instagramHandle: "@kinoraneurostore",
      email: "contacto@kinora.com",
    },
    commerce: mxCommerce,
  },
  CR: {
    market: "CR",
    country: "Costa Rica",
    locale: "es-CR",
    currency: "CRC",
    currencySymbol: "₡",
    deliveryText: "Información de entrega para Costa Rica pendiente de confirmación.",
    contact: {
      whatsapp: null,
      whatsappDisplay: null,
      instagramUrl: null,
      instagramHandle: null,
      email: null,
    },
    commerce: crCommerce,
  },
};
const requestedMarket = import.meta.env?.VITE_MARKET?.trim().toUpperCase();
export const activeMarket = Object.hasOwn(marketConfigs, requestedMarket) ? requestedMarket : "MX";
export const marketConfig = marketConfigs[activeMarket];
